export const personalInfo = {
  name: "Devansh Sharma",
  handle: "Elvis280",
  title: "AI Engineer & Full-Stack Developer",
  email: "devansh28sharma@gmail.com",
  github: "https://github.com/Elvis280",
  linkedin: "https://www.linkedin.com/in/devansh-sharma28/",
  twitter: "https://x.com/Devansh280",
  location: "India",
  bio: "Building production-grade AI systems, autonomous agents, and scalable full-stack applications. Passionate about LLMs, RAG pipelines, and turning complex AI research into real products.",
  objective: "Seeking to leverage my expertise in AI/ML and full-stack development to build intelligent systems that solve real-world problems at scale.",
  avatar: "/Dev.png",
  cv: "/Devansh_Sharma_CV.pdf",
  roles: [
    "AI Engineer",
    "LLM Systems Builder",
    "Full-Stack Developer",
    "Automation Architect",
    "RAG Pipeline Engineer",
  ],
};

export const stats = [
  { label: "Projects Built", value: "10+" },
  { label: "AI Systems", value: "5+" },
  { label: "Certifications", value: "8" },
  { label: "Tech Stack", value: "20+" },
];

export const skillCategories = [
  {
    id: "ai-ml",
    label: "AI / ML",
    icon: "Brain",
    color: "from-violet-500 to-purple-600",
    skills: ["LLMs", "RAG Pipelines", "AI Agents", "Machine Learning", "TensorFlow", "PyTorch", "LangChain"],
  },
  {
    id: "llm-apis",
    label: "LLM & APIs",
    icon: "Zap",
    color: "from-cyan-400 to-blue-500",
    skills: ["OpenAI API", "Gemini API", "LangChain", "LlamaIndex", "Prompt Engineering", "Fine-tuning"],
  },
  {
    id: "backend",
    label: "Backend",
    icon: "Server",
    color: "from-emerald-400 to-teal-500",
    skills: ["Python", "FastAPI", "Flask", "REST APIs", "MySQL", "PostgreSQL"],
  },
  {
    id: "frontend",
    label: "Frontend",
    icon: "Monitor",
    color: "from-orange-400 to-pink-500",
    skills: ["React", "Next.js", "TypeScript", "JavaScript", "Tailwind CSS", "HTML/CSS"],
  },
  {
    id: "automation",
    label: "Automation",
    icon: "GitBranch",
    color: "from-yellow-400 to-orange-500",
    skills: ["n8n", "Zapier", "Workflow Automation", "Web Scraping", "Data Pipelines"],
  },
  {
    id: "cloud-devops",
    label: "Cloud & DevOps",
    icon: "Cloud",
    color: "from-blue-400 to-indigo-500",
    skills: ["Google Cloud", "Vercel", "Docker", "Git", "GitHub", "CI/CD"],
  },
];

export const projects = [
  {
    id: "nexa-ai",
    title: "NEXA_AI",
    subtitle: "AI Agent Platform",
    description: "AI-powered conversational agent platform with agentic workflows, LLM integration, multi-step reasoning, and scalable backend infrastructure.",
    image: "/images/nexa-ai.png",
    gradient: "from-violet-600 to-indigo-700",
    tech: ["Python", "LLM APIs", "Automation", "Agents", "FastAPI"],
    github: "https://github.com/Elvis280/NEXA_AI",
    demo: "https://nexa-ai-n6lv.onrender.com/",
    featured: true,
    category: "AI System",
  },
  {
    id: "carbontwin",
    title: "CARBONTWIN",
    subtitle: "Environmental Analytics",
    description: "Full-stack environmental tracking platform with real-time carbon footprint analytics, interactive data visualization, and predictive insights.",
    image: "/images/CarbonTwin.png",
    gradient: "from-emerald-500 to-teal-600",
    tech: ["JavaScript", "HTML", "CSS", "Web App", "Charts"],
    github: "https://github.com/Elvis280/CarbonTwin",
    demo: "https://elvis280.github.io/CarbonTwin/",
    featured: true,
    category: "Web App",
  },
  {
    id: "agrowise",
    title: "AGROWISE",
    subtitle: "AI Agricultural Assistant",
    description: "AI-driven agricultural assistant with FastAPI backend, ML models for crop recommendations, soil analysis, and optimized database queries.",
    image: "",
    gradient: "from-green-500 to-emerald-600",
    tech: ["Python", "FastAPI", "AI APIs", "ML", "Backend"],
    github: "",
    demo: "",
    featured: false,
    category: "AI System",
  },
  {
    id: "ecowaste",
    title: "ECOWASTE",
    subtitle: "Smart Waste Classifier",
    description: "React-based waste categorization system with intelligent classification, real-time state management, and sustainability tracking.",
    image: "/images/EcoWaste.png",
    gradient: "from-teal-500 to-cyan-600",
    tech: ["JavaScript", "React", "Web App", "Sustainability"],
    github: "https://github.com/Elvis280/EcoWaste",
    demo: "https://eco-waste-roan.vercel.app/",
    featured: false,
    category: "Web App",
  },
  {
    id: "crud-flask",
    title: "CRUD-FLASK",
    subtitle: "Admin Dashboard API",
    description: "Full-stack admin dashboard with RESTful API endpoints, MySQL database integration, JWT authentication, and complete CRUD operations.",
    image: "",
    gradient: "from-orange-500 to-red-600",
    tech: ["Python", "Flask", "MySQL", "REST API", "JWT"],
    github: "https://github.com/Elvis280/CRUD-Flask",
    demo: "https://elvis04.pythonanywhere.com/",
    featured: false,
    category: "Backend",
  },
];

export const experiences = [
  {
    id: "algozenith",
    role: "Technical Lead",
    organization: "AlgoZenith Student Chapter",
    period: "Aug 2025 – Present",
    current: true,
    description: "Leading technical workshops on algorithms, data structures, and competitive programming. Architecting coding challenges, mentoring students, and building automated evaluation systems for programming contests.",
    tags: ["Algorithms", "DSA", "Mentoring", "Automation"],
  },
  {
    id: "gfg",
    role: "Faculty Connect & PR Lead",
    organization: "GeeksforGeeks Student Chapter",
    period: "Oct 2024 – Present",
    current: true,
    description: "Coordinating technical events and hackathons, managing stakeholder communications, and previously served as Technical Coordinator building full-stack web applications for chapter activities.",
    tags: ["Events", "Full-Stack", "PR", "Hackathons"],
  },
  {
    id: "srdt",
    role: "Python Full-Stack Trainee",
    organization: "SRDT Training Program",
    period: "2024",
    current: false,
    description: "Built full-stack applications using Python and Flask. Developed RESTful APIs with authentication, implemented MySQL database schemas, CRUD operations, and deployed optimized web applications.",
    tags: ["Python", "Flask", "MySQL", "REST API"],
  },
];

export const certificates = [
  {
    id: "google-ai-day",
    name: "Agentic AI Day",
    issuer: "Google Cloud Skill Boost",
    date: "2025",
    image: "/certificates/Agentic AI Day.png",
    url: "https://certificate.hack2skill.com/user/aidayideasubmission/2025H2S06AID-I14934",
    skills: ["Agentic AI", "Google Cloud", "AI Agents", "LLM"],
    color: "from-blue-500 to-cyan-400",
  },
  {
    id: "kaggle-ai-agents",
    name: "AI Agents Intensive",
    issuer: "Kaggle × Google",
    date: "2024",
    image: "/certificates/AI Agents Intensive Course with Google.png",
    url: "https://www.kaggle.com/certification/badges/elvis2804/105",
    skills: ["AI Agents", "Machine Learning", "Python"],
    color: "from-cyan-500 to-teal-400",
  },
  {
    id: "neo4j",
    name: "Neo4j Certified",
    issuer: "Neo4j Graph Academy",
    date: "2024",
    image: "/certificates/Neo4j.png",
    url: "https://graphacademy.neo4j.com/c/3439211c-c06e-490e-bee2-66dbcd2016e7/",
    skills: ["Graph Databases", "Cypher", "Neo4j"],
    color: "from-violet-500 to-purple-400",
  },
  {
    id: "hela-blockchain",
    name: "HeLa Labs Blockchain",
    issuer: "Hela Labs",
    date: "2024",
    image: "/certificates/HeLa Labs Blockchain.png",
    url: "https://credsverse.com/credentials/4dcce8fe-ba40-435f-b881-6e9260f63258",
    skills: ["Blockchain", "Web3", "Smart Contracts"],
    color: "from-emerald-500 to-green-400",
  },
  {
    id: "hackerrank-python",
    name: "Python Programming",
    issuer: "HackerRank",
    date: "2024",
    image: "/certificates/Programming Using Python.png",
    url: "https://www.hackerrank.com/certificates/812232d025d9",
    skills: ["Python", "Algorithms", "Problem Solving"],
    color: "from-orange-500 to-yellow-400",
  },
  {
    id: "ai-builders-lab",
    name: "AI Builders Lab",
    issuer: "Hack2skill",
    date: "2024",
    image: "/certificates/AI Builders Lab.png",
    url: "https://certificate.hack2skill.com/user/aibuilderslab2/2024H2S10AIBL-P200273",
    skills: ["AI Development", "ML", "Model Training"],
    color: "from-pink-500 to-rose-400",
  },
  {
    id: "tableau-analytics",
    name: "Data Analytics & Tableau",
    issuer: "Jobaaj Learnings",
    date: "2024",
    image: "/certificates/Data Analytics with Specialization in Tableau.png",
    url: "https://www.jobaajlearnings.com//certificate?file=certificate-329792-37-0.jpeg",
    skills: ["Tableau", "Data Viz", "Business Intelligence"],
    color: "from-blue-500 to-indigo-400",
  },
  {
    id: "tata-crucible",
    name: "TATA Crucible Quiz",
    issuer: "Unstop",
    date: "2024",
    image: "/certificates/TATA Crucible Campus Quiz.png",
    url: "https://unstop.com/certificate-preview/991da870-b4e4-4edb-864f-058a2aa4f4d1",
    skills: ["Critical Thinking", "Problem Solving"],
    color: "from-slate-500 to-gray-400",
  },
];

export const aiPlayground = [
  {
    id: "agent-systems",
    title: "Autonomous Agent Systems",
    description: "Built multi-agent orchestration systems using LangChain and OpenAI. Agents handle research, reasoning, tool-use, and task delegation autonomously.",
    icon: "Bot",
    gradient: "from-violet-500 to-purple-600",
    tags: ["LangChain", "OpenAI", "Multi-Agent", "Tool Use"],
    status: "Production",
  },
  {
    id: "rag-pipelines",
    title: "RAG Pipeline Architecture",
    description: "Designed and deployed Retrieval-Augmented Generation pipelines with vector databases, semantic search, and custom chunking strategies for domain-specific knowledge.",
    icon: "Database",
    gradient: "from-cyan-500 to-blue-600",
    tags: ["Vector DB", "Embeddings", "Semantic Search", "LLMs"],
    status: "Production",
  },
  {
    id: "automation",
    title: "AI Automation Workflows",
    description: "Created end-to-end automation workflows using n8n and custom Python scripts. Connecting LLMs with APIs, databases, and third-party services for intelligent automation.",
    icon: "Workflow",
    gradient: "from-emerald-500 to-teal-600",
    tags: ["n8n", "Python", "APIs", "Workflow Automation"],
    status: "Active",
  },
];
